// Generated by https://quicktype.io

export interface ICreateExpenseTypeResponse {
    data: {
        id: number;
        name: string;
        description: null;
        status: boolean;
    }
    meta: any[];
    rels: any[];
}

